### ISSUE TITLE
K error

### ISSUE THREAD

**Issue by yqlwqj** [jagennath-hari/RGBD-3DGS-SLAM#3]
Hi,  I was running this "python slam.py --config configs/rgbd/tum/fr3_office.yaml" . but have this issue happens 

Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
MonoGS: saving results in results/datasets_tum/2024-07-21-09-46-21
/home/rsa-key-20230501/project/RGBD-3DGS-SLAM/UniDepth/unidepth/models/unidepthv2/unidepthv2.py:47: UserWarning: Resolution level is not set. Using max resolution. You can tradeoff resolution for speed by setting a number in [0,10]. This can be achieved by setting model's `resolution_level` attribute.
  warnings.warn(
Traceback (most recent call last):
  File "/home/rsa-key-20230501/project/RGBD-3DGS-SLAM/MonoGS/slam.py", line 259, in <module>
    slam = SLAM(config, save_dir=save_dir)
  File "/home/rsa-key-20230501/project/RGBD-3DGS-SLAM/MonoGS/slam.py", line 63, in __init__
    self.dataset = load_dataset(
  File "/home/rsa-key-20230501/project/RGBD-3DGS-SLAM/MonoGS/utils/dataset.py", line 720, in load_dataset
    return TUMDataset(args, path, config)
  File "/home/rsa-key-20230501/project/RGBD-3DGS-SLAM/MonoGS/utils/dataset.py", line 441, in __init__
    parser = TUMParser(dataset_path)
  File "/home/rsa-key-20230501/project/RGBD-3DGS-SLAM/MonoGS/utils/dataset.py", line 63, in __init__
    self.load_poses(self.input_folder, frame_rate=32)
  File "/home/rsa-key-20230501/project/RGBD-3DGS-SLAM/MonoGS/utils/dataset.py", line 141, in load_poses
    intrinsics = predictions["K"].squeeze().cpu().numpy()  # Convert to 2D numpy array on the CPU
KeyError: 'K'

   May you point out how to fix this ? 

thanks

ben

**Comment by jagennath-hari** [comment]
That is strange because UniDepthV2 should be using the key 'K'. Could you try with predictions["intrinsics"].squeeze().cpu().numpy() instead? Let me know if you come across any other issues.

**Comment by yqlwqj** [comment]
looks it 's going now.
